public class BasicJavaTest {

    public static void main(String[] args) {
        BasicJava tester = new BasicJava();
        // tester.print();
        // System.out.println("<-------------------------------------------------------------->");
        // tester.printOdd();
        // System.out.println("<-------------------------------------------------------------->");
        // System.out.println(tester.sigma());
        // int[] array = {1, 3, 5, 7, 9, 13};
        // tester.iterateArray(array);
        // int[] testArr = {-1, -8, -6, -100, -10, -200};
        // tester.findMax(testArr);
        System.out.println(tester.oddNumbers());
    }
}